language: c
sudo: required
dist: trusty
script:
  - sudo apt-get install -y linux-headers-`uname -r`
  - make x86_64
  - sudo insmod Release/r0mod.ko

after_success:
  - bash <(curl -s https://codecov.io/bash)
